---
- name: Deploy app
  hosts: all

  tasks:
    - name: Create directory
      file:
        path: ~/app
        state: directory

    - name: Copy app
      copy:
        src: "{{ repo_path }}/app/"
        dest: ~/app/
      

    - name: Run app
      command: sh ~/app/app_run.sh