---
- name: Deploy my app
  hosts: myapp

  tasks:
    - name: Create directory
      file:
        path: ~/app
        state: directory

    - name: Copy files
      copy:
        src: ../app/hello.py
        dest: ~/app/hello.py

    - name: Copy script
      copy:
        src: ../app/app_run.sh
        dest: ~/app/app_run.sh
        mode: '0777'

    - name: Run app
      command: sh ~/app/app_run.sh
